title = "repo gitleaks config"

[allowlist]
description = "global allowlist"
paths = [
  '''^docs/''',
  '''^testdata/'''
]

# Include default gitleaks rules so we don't accidentally disable scanning
[extend]
useDefault = true
